<!DOCTYPE html>
<html lang="en">
<head>
<style>
input[value="register"],
input[value="Add course"] {
    background-color: blue;
    color: white;
    padding: 5px 12px;
    border: none;
    border-radius: 4px;
}

</style>


</head>
<body>
    <center>
    <h1>Student Registration Section</h1>
    <table>
    <tr>
        <td>
         Full Name:
</td>
</tr>
<tr>
<td>
<input type="text">
</td>
</tr>
<tr>
    <td>
     Email:
    </td>
</tr>
<tr>
    <td>
    <input type="text">
</td>
</tr>

<tr>
    <td>
     Password:
</td></tr>
<tr>
<td>
<input type="text">
</td>
</tr>

<tr>
    <td>
     Comfirm Password:
</td></tr>

<td>
<input type="text">

</td>
</tr>
<tr><td>
    <input type="button"value="register">
</td></tr>

</body>
<body>
    <tr><td>
    <p>Registration Successful!</p>
    <p id="demo"></p>
</td></tr>
<tr><td>
    Name:
</td></tr>
<tr>
    <td>
        <input type="text">
</td></tr>
<tr><td>
       Email:
</td></tr>
<tr>
    <td>
        <input type="text">
</td></tr>
</body>

    <tr>
        <td>
        Course Name:
</td>
</tr>
<tr>
<td>
<input type="text">
</td>
</tr>

<tr>
    <td>
   <input type="button"value="Add course">

</td>
</tr>

</html>
